version: '3'

services:
    rabbitmq:
      image: rabbitmq:3-management
      hostname: "rabbit_node_2"
      ports:
        - "15672:15672"
        - "5672:5672"
      environment:
        RABBITMQ_DEFAULT_USER: "test1"
        RABBITMQ_DEFAULT_PASS: "test1"
      networks:
        - mynet1
    mongo:
      image: mongo
      restart: always
      container_name: "mongodb"
      volumes:
       - mydate:/data/db
      ports:
        - "27017:27017"
      networks:
        - mynet1
    mysql:
      image: mysql:latest
      restart: always
      container_name: "mysqldb"
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "root"
      volumes:
        - mysqldata:/var/lib/mysql

volumes:
  mydate:
  mysqldata:
networks:
  mynet1:
    driver: bridge